spring.application.name=prod-ready-features

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-features?useSSL=false
spring.datasource.username=root
spring.datasource.password=Manju@11513

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=ALWAYS
#spring.sql.init.data-locations=classpath:data.sql


server.port=9000
employeeService.base.url = http://localhost:8080/

#logging configurations
logging.level.com.example.prod_ready_features.clients=trace
logging.level.com.example.prod_ready_features.configs=info
#logging.level.root=debug

logging.pattern.console=%d{dd-mm-yyyy hh::mm:ss} [%level] [%c{2.}] --- %m%n

logging.file.name=application.log

#actuator configurations
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=Nishikant Prasad
info.app.version=1.0.0
info.app.documentation=https://codingshuttle.com/docs